export const SIGNUP_STARTED = "SIGNUP_STARTED"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILED  = "SIGNUP_FAILED"

export const LOGIN_STARTED = "LOGIN_STARTED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED  = "LOGIN_FAILED"
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS"
export const AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED"

export const LOGOUT_STARTED = "LOGOUT_STARTED"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED  = "LOGOUT_FAILED"

export const ERROR_OCCURED = "ERROR_OCCURED"
export const ERROR_CLEANED = "ERROR_CLEANED"

export const POPUP_SHOW = "POPUP_SHOW"
export const POPUP_HIDE = "POPUP_HIDE"

export const POPUP_INPUT_CLEAR = "POPUP_INPUT_CLEAR"
export const POPUP_INPUT_SET = "POPUP_INPUT_SET"

export const POPUP_TYPE_SET = "POPUP_TYPE_SET";

export const POPUP_TEXT_SET = "POPUP_TEXT_SET"

export const POPUP_INPUT_ENTERED = "POPUP_INPUT_ENTERED" 

export const ADD_PROJECT_START = "ADD_PROJECT_START"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAILED = "ADD_PROJECT_FAILED"

export const POPUP_BUTTON_HANDLER_SET = "POPUP_BUTTON_HANDLER_SET"

export const GET_LISTS_START = "GET_LISTS_START"
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS"
export const GET_LISTS_FAILED = "GET_LISTS_FAILED"

export const ADD_LIST_START = "ADD_LIST_START"
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS"
export const ADD_LIST_FAILED = "ADD_LIST_FAILED"

export const ADD_NEW_PROJECT_SET_TO_TRUE = "ADD_NEW_PROJECT_SET_TO_TRUE"
export const ADD_NEW_LIST_SET_TO_TRUE = "ADD_NEW_LIST_SET_TO_TRUE"
export const ADD_NEW_ITEM_SET_TO_TRUE = "ADD_NEW_ITEM_SET_TO_TRUE"

export const GET_PROJECT_START = "GET_PROJECT_START"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"
export const GET_PROJECT_FAILED = "GET_PROJECT_FAILED"

export const ADD_ITEM_TO_PROJECT_START = "ADD_ITEM_TO_PROJECT_START"
export const ADD_ITEM_TO_PROJECT_SUCCESS = "ADD_ITEM_TO_PROJECT_SUCCESS"
export const ADD_ITEM_TO_PROJECT_FAILED = "ADD_ITEM_TO_PROJECT_FAILED"

export const ADD_NEW_NEXT_ACTION_START = "ADD_NEW_NEXT_ACTION_START"
export const ADD_NEW_NEXT_ACTION_SUCCESS = "ADD_NEW_NEXT_ACTION_SUCCESS"
export const ADD_NEW_NEXT_ACTION_FAILED = "ADD_NEW_NEXT_ACTION_FAILED"

export const GET_NEXT_ACTIONS_START = "GET_NEXT_ACTIONS_START"
export const GET_NEXT_ACTIONS_SUCCESS = "GET_NEXT_ACTIONS_SUCCESS"
export const GET_NEXT_ACTIONS_FAILED = "GET_NEXT_ACTIONS_FAILED"

export const GET_NEXT_ACTIONS_FOR_PROJECT_START = "GET_NEXT_ACTIONS_FOR_PROJECT_START"
export const GET_NEXT_ACTIONS_FOR_PROJECT_SUCCESS = "GET_NEXT_ACTIONS_FOR_PROJECT_SUCCESS"
export const GET_NEXT_ACTIONS_FOR_PROJECT_FAILED = "GET_NEXT_ACTIONS_FOR_PROJECT_FAILED"

export const SET_NEXT_ACTIONS_TO_NULL = "SET_NEXT_ACTIONS_TO_NULL"

export const DELETE_PROJECT_START = "DELETE_PROJECT_START";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED"

export const ACTIVATE_PROJECT_SUCCESS = "ACTIVATE_PROJECT_SUCCESS"
export const ACTIVATE_PROJECT_FAILED = "ACTIVATE_PROJECT_FAILED"

export const DELETE_NEXT_ACTION_START = "DELETE_NEXT_ACTION_START"
export const DELETE_NEXT_ACTION_SUCCESS = "DELETE_NEXT_ACTION_SUCCESS"
export const DELETE_NEXT_ACTION_FAILED = "DELETE_NEXT_ACTION_FAILED"
export const DELETE_NEXT_ACTION_ALL_SUCCESS = "DELETE_NEXT_ACTION_ALL_SUCCESS"